sudo: false
language: java
jdk:
- oraclejdk8
before_install:
  - git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
  - cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: Bstnlrvg43uQLS+0hvC4AvatiuafyKLV0WPOt+tKvFJcwIIEAs0w674+m2nRmkhGU6fJtr+/MPrc/rDmRoiPbeqOpY4avPn2q6SAICrw0txkySp02rYcay/JKzNiqOG4PhbxGYiyS7FwBPnVVzvm+529OuT6e8wfsaf4UrFTht7XRtkJkSzigCRjI/DFAOn7UM8UadjomhxF+9gDPBcdP7xD/SYjif+yFdnkS/Mgt/UxW725Dikqxd9CfW89WSqY/2V+yKNDvzTaocYU5C1eTH5z75V/RYudzhqNwpIC2pkoqDxgQtXSU0FzCFlIruWAx5aE/GuU9FxNZd6Do5pczlkBrqODFYtsS0jebxAB1MpDNQhx2G8sMQQ7IG8BomZPAuVocfSodiBT2uB29SoH9EPl6frkq0s81ieRN8/m5ubrzPj4rmf8b9TPUb5xYWSr1sUx5Ie6oGldDCZxzvw45dX2/QemMuTYZ3qdhr6KZs6l1BCi6RulMZZukA9JnLgq050rQp7c1Rq/K1zf496Pwdx0HQYNmWcChx2d1b1RYyZUjQVJTypV9gYkrPZJsofqgexLR5Hcw0dMo6LjPGSb7Ou/8gBRJBxnxuW3jPouwLe2KYO0aFItjEQW47l8dLQtvaIQwR7K4S7T4PxAbwjQA41lfzGliZnzPnEv0cZlGAI=
  - secure: ja+hzG3evNq7L8FlPthZequFFozU0u7M+JAqEpnytESRBfB+t2ZkCBVp6/I7037xSH1e9mqQ7y1s6E/OpdIh/MlXwkB2MsiCWxBBW/JJzgS/Q+8ssgal8rEeC7qhRXeWdOcEo0uz/TDXXaCA8jUQm0+8EhDPb2lG90kopMZWd6bEFQUTYuHor3vZnro/j0UGVsuoluK5Me15NF38BJxNw6MasPZt6bKpunb02etVFGNLJKfAi0h4gYPpzKGf4fTa9FeW/rSsop8JbRuVBrkkRaegggXBURte2AsuhtrFAPcGTRO6zL3MWGpgEQ0qLTEeZ1VGvaPlAtXoYr+FH9eJodfNkOtBlDlUElsYVWTDnA9ZVqUUzROlTX1ztMCI7bJRNEi6f452xZmIbrbf+f0kdOw82tWuMDg3MguCIqP1em/+npuw1fS56rQ+LlYL3Ul+6GIrd9KvrUbgm3mX6Qfxju8hrztGAZJqVHrih7cBxnl3bD0muOOUKL/9jEEg0eFy2JMjiYOLunkM/1Kpsoksp1iW8EbxyLhIrCRP+Hy2Pim7V1/6T3eBmY8NNzd86Oaa6ARcJtGkjwaw3bKcABVjFLVt2LOLiMIg9zfQU3OtTzPDZ+IKtQdiCeY5MlQCFg8xWOBckHpUertHFrAWUOUE0GzXk/m/eC67n8w7NeCTbps=
